name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install Flask pytest pytest-cov flake8 bandit
      - name: Lint (flake8)
        run: flake8 . || true
      - name: Security (bandit)
        run: bandit -q -r . || true
      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -v
