name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit

      - name: Lint (flake8)
        run: flake8 --config=.flake8 .

      - name: Security scan (bandit)
        run: bandit -r . -q || true

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=app --cov-report=term-missing:skip-covered --cov-report=xml

      - name: Enforce coverage >= 87% (only on 3.11)
        if: matrix.python-version == '3.11'
        run: |
          python - <<'PY'
import xml.etree.ElementTree as ET, sys
pct = float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100
print(f"Total coverage: {pct:.2f}%")
sys.exit(0 if pct >= 87.0 else 1)
PY

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
